spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: toor
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    # Ultilizar apenas para desenvolvimento
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true